name: mastodon-civ-quote-bot

on:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependancy
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bot
        run: |
          python civbot.py

      env:
        MASTODON_BASE_URL: \$
        MASTODON_ACCESS_TOKEN: \$
